apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-deployment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Davidd30/End-to-End-DevSecOps-Tetris-Project'
    targetRevision: deploy
    path: 'Tetris-V2/k8s' 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tetris
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
